"""Bakeoff F15 oracle (glm-5p2 agentic gate) — Done items auto-delete after a retention window.

Items left in status='done' for longer than a configurable window are permanently purged
(Gmail-trash style). The age is measured from when the item entered Done — which the schema
records as `processed_utc` for an item currently in status='done' (there is no separate
done_at column). Purge uses the direct-delete path and, like decay, MUST NOT enqueue a
Reddit unsave.

Contract the executor must implement (edit SOURCE only — do NOT edit this file):
  * db.purge_done(conn, *, now: int | None = None, apply: bool = False) -> dict
      - selects status='done' items whose processed_utc < now - retention_days*86400
      - retention_days reads setting "done_retention_days", default 30
      - dry-run (apply=False) returns {"total": N, "applied": False, ...} and changes nothing
      - apply=True permanently deletes the matched rows (direct-delete path) and returns
        {"total": N, "applied": True, ...}
      - MUST NOT enqueue any reddit_unsave row (mirror the db.decay safety invariant)

Authored RED on branch bakeoff/oracle-F15.
"""

from content_hoarder import db, models

DAY = 86400
NOW = 1_000_000_000


def _seed(conn, sid, *, status, processed_utc=None, source="reddit"):
    it = models.new_item(source=source, source_id=sid, kind="post", title=sid)
    db.merge_upsert(conn, it)
    fn = f"{source}:{sid}"
    conn.execute(
        "UPDATE items SET status=?, processed_utc=? WHERE fullname=?",
        (status, processed_utc, fn),
    )
    conn.commit()
    return fn


def test_f15_dryrun_counts_only_old_done(conn):
    old = _seed(conn, "t3_old", status="done", processed_utc=NOW - 40 * DAY)
    _seed(conn, "t3_recent", status="done", processed_utc=NOW - 5 * DAY)
    _seed(conn, "t3_inbox", status="inbox", processed_utc=None)
    _seed(conn, "t3_keep_old", status="keep", processed_utc=NOW - 40 * DAY)

    res = db.purge_done(conn, now=NOW, apply=False)
    assert res["applied"] is False
    assert res["total"] == 1  # only the old DONE item qualifies
    assert db.get_item(conn, old) is not None  # dry run deletes nothing


def test_f15_apply_purges_only_old_done(conn):
    old = _seed(conn, "t3_old", status="done", processed_utc=NOW - 40 * DAY)
    recent = _seed(conn, "t3_recent", status="done", processed_utc=NOW - 5 * DAY)
    inbox = _seed(conn, "t3_inbox", status="inbox")
    keep_old = _seed(conn, "t3_keep_old", status="keep", processed_utc=NOW - 40 * DAY)

    res = db.purge_done(conn, now=NOW, apply=True)
    assert res["applied"] is True and res["total"] == 1
    assert db.get_item(conn, old) is None        # old done -> purged
    assert db.get_item(conn, recent) is not None  # recent done -> kept
    assert db.get_item(conn, inbox) is not None   # inbox -> kept
    assert db.get_item(conn, keep_old) is not None  # old but not done -> kept


def test_f15_purge_does_not_enqueue_unsave(conn):
    # even with unsave-on-done enabled, a retention purge must not queue a Reddit unsave
    db.set_setting(conn, "reddit_unsave_on_done", "1")
    old = _seed(conn, "t3_old", status="done", processed_utc=NOW - 40 * DAY)

    db.purge_done(conn, now=NOW, apply=True)
    assert db.get_item(conn, old) is None
    pending = conn.execute(
        "SELECT COUNT(*) FROM reddit_unsave WHERE state='pending'"
    ).fetchone()[0]
    assert pending == 0, "purging Done items must NOT enqueue a Reddit unsave"


def test_f15_window_is_configurable(conn):
    _seed(conn, "t3_mid", status="done", processed_utc=NOW - 10 * DAY)
    # default 30-day window: a 10-day-old Done item is NOT yet purgeable
    assert db.purge_done(conn, now=NOW, apply=False)["total"] == 0
    # shrink the retention window to 7 days -> it now qualifies
    db.set_setting(conn, "done_retention_days", "7")
    assert db.purge_done(conn, now=NOW, apply=False)["total"] == 1
